# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-sing-nod
name: Node.js

on:
  push:
    branches: main
  workflow_dispatch:
  
env:
  test: 'true'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name : input
      id: call
      run: |
        echo "::set-output name=firstoutput::${{ env.test }}"
    outputs:
      firstoutput-test: ${{ steps.call.outputs.firstoutput }}
  
  calling:
    uses: tanishchoudhary/newone/.github/workflows/env.yml@main
    needs: build
    with:
      firstoutput-test: ${{ needs.build.outputs.firstoutput-test }}  
    
  
  check:
    runs-on: ubuntu-latest
    needs: calling
    steps:
      - run: echo ${{ needs.calling.outputs.second_output }}
  check-true:
    runs-on: ubuntu-latest
    needs: calling
    if: always() && ${{ needs.calling.outputs.second_output == 'true' }}
    steps:
      - run: echo "true"
  
  check-false:
    runs-on: ubuntu-latest
    needs: calling
    if: always() && ${{ needs.calling.outputs.second_output == 'false' }}
    steps:
      - run: echo "false"

 
