name: helloo

on: 
  push:
    branches:  ma
  workflow_call:
env:
  serv: hello, hellooo
jobs:
  bro:
  
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}   
    steps:
      - name: 'checkout coode ${{ github.REF }}'
        uses: actions/checkout@v2.4.0
