name: helloo

on: 
  push:
    branches:  main
  workflow_call:
env:
  serv: hello, hellooo
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: A/B Check
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Your are not supposed to run in main"
          exit 1

  bro:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}   
    steps:
      - name: 'checkout coode ${{ github.REF }}'
        uses: actions/checkout@v2.4.0
